openapi: 3.0.0
info:
  title: CADDE v3 Specification 提供者 データ交換I/F(CADDE)
  version: "3.0"
servers:
- url: /
paths:
  /cadde/api/v1/file:
    get:
      tags:
      - Files
      summary: API. ファイル取得(cadde)
      description: |-
        CADDEインタフェースを用いてファイルを取得する。

        Response:
        * 処理が成功した場合は200を返す。
        * 処理に失敗した場合は、2xx以外を返す。Responsesセクション参照。
      operationId: files
      parameters:
      - name: x-cadde-resource-url
        in: header
        description: リソースURL
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-resource-api-type
        in: header
        description: |-
         リソース提供手段識別子
         FTP、HTTP、NGSIのいずれかを指定する(FTP:file/ftp, HTTP:file/http, NGSI:api/ngsi)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        description: 認証トークン
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-options
        in: header
        description: |-
         NGSIオプション
         ("key1:value1,key2:value2・・・"形式)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: |-
           呼び出し時のリソース提供手段識別子が"file/ftp","file/http"の場合はダウンロードしたファイル "api/ngsi"の場合はJSON形式、また、ヘッダx-cadde-optionsにレスポンスヘッダ情報、ヘッダ情報に識別情報を設定
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                x-content-type: application/octet-stream
              example: text or csv or pdf etc..
          headers:
            x-cadde-provenance:
              description: 来歴管理I/Fから受領した識別情報 識別情報を受領しなかった場合は''(空文字)を設定する
              schema:
                type: string
            others:
              description: NGSIサーバにて設定されたヘッダー情報
              schema:
                type: string
        "400":
          description: パラメータ不正の場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: Missing header parameter (パラメータ名)
                    status: 400
                    title: Bad Request
                    type: about:blank
        "401":
          description: "認証認可処理での認証失敗の場合のエラーメッセージ"
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: 利用者確認処理でエラーが発生しました。
                    status: 401
                    title: ""
                    type: ""
        "403":
          description: ベーシック認証に失敗した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: FTP接続時に認証に失敗しました。サイト管理者に問い合わせてください。
                    status: 403
                    title: ""
                    type: ""
        "404":
          description: |-
            FTP接続で指定したディレクトリにファイルが存在しない場合のエラーメッセージ、または、HTTPS接続で指定したURLにファイルが存在しない場合のエラーメッセージ。
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: ファイルが見つかりませんでした。サイト管理者に問い合わせてください。
                    status: 404
                    title: ""
                    type: ""
        "408":
          description: |-
            タイムアウトが発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラーが発生しました。エラー:(エラー内容)
                    status: 408
                    title: ""
                    type: ""
        "500":
          description: サーバーの内部処理で異常が発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラーが発生しました。エラー:(エラー内容)
                    status: 500
                    title: ""
                    type: ""
      x-openapi-router-controller: swagger_server.controllers.files_controller
components:
  schemas:
    ErrorResponse:
      title: HTTPステータスコードが4xx、500の場合のレスポンス
      required:
      - detail
      - status
      type: object
      properties:
        detail:
          type: string
          description: エラーメッセージ
        status:
          type: number
          description: HTTPステータスコード
        title:
          type: string
          description: タイトル
        type:
          type: string
          description: タイプ

