openapi: 3.0.0
info:
  title: CADDE v3 Specification 提供者 カタログ検索IF
  version: "3.0"
servers:
- url: /
paths:
  /api/3/action/package_search:
    get:
      tags:
      - Search
      summary: API. カタログ検索(詳細検索)
      description: |-
        提供者カタログサイトからCKANカタログ情報を取得する。
        
        Response:
        * 処理が成功した場合は200を返す。
        * 処理に失敗した場合は、2xx以外を返す。場合によりエラーを示すペイロードがつく場合もある。Responsesセクションを参照すること。
      operationId: search
      parameters:
      - name: q
        in: query
        description: |-
         CKAN検索条件クエリ
         CKAN APIに準拠
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: 認証トークン
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: CKANから取得したカタログ情報
          content:
            application/json:
              example:
                help: https:/xxx/api/3/action/help_show?name=package_search
                success: true
                result:
                  count: 0
                  sort: score desc, metadata_modified desc
                  facets: {}
                  results: {}
                  search_facets: {}
        "400":
          description: パラメータ不正の場合のエラーメッセージ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    error-message: パラメータが不正です。
        "401":
          description: "認証認可処理での認証失敗の場合のエラーメッセージ"
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: 利用者確認処理でエラーが発生しました。
                    status: 401
                    title: ""
                    type: ""
        "408":
          description: |-
            リクエストタイムアウト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: リクエストタイムアウトによるエラーが発生しました。
                    status: 408
                    title: ""
                    type: ""
        "500":
          description: サーバーの内部処理で異常が発生した場合のエラーメッセージ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    error-message: エラーが発生しました。エラー:(エラー内容)
      x-openapi-router-controller: swagger_server.controllers.search_controller
components:
  schemas:
    ErrorResponse:
      title: HTTPステータスコードが4xx、500の場合のレスポンス
      required:
      - error-message
      type: object
      properties:
        error-message:
          type: string
          description: エラーメッセージ

