openapi: 3.0.0
info:
  title: CADDE v1 Specification 利用者 カタログ検索I/F
  version: "1.0"
servers:
- url: /
paths:
  /api/3/action/package_search:
    get:
      tags:
      - Search
      summary: API.04 カタログ検索
      description: |-
        横断検索、詳細検索を判定し、
        横断検索サイトまたは提供者カタログサイトからカタログ情報を取得する
        Response:
        * 処理が成功した場合は200を返す
        * 処理に失敗した場合は、2xx以外を返す。Responsesセクション参照。
      operationId: search
      parameters:
      - name: q
        in: query
        description: CKAN検索条件クエリ CKAN APIに準拠
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: x-cadde-search
        in: header
        description: 横断検索、詳細検索を指定する(横断検索:meta、詳細検索:detail)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-provider-connector-url
        in: header
        description: 提供者コネクタURL x-cadde-searchがmetaの場合は不要、detailの場合は必須
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        description: 契約トークン
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: CKANから取得したカタログ情報を返す.
          content:
            application/json:
              example:
                help: https:/xxx/api/3/action/help_show?name=package_search
                success: true
                result:
                  count: 0
                  sort: score desc, metadata_modified desc
                  facets: {}
                  results: {}
                  search_facets: {}
        "400":
          description: パラメータ不正の場合のエラーメッセージ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: Missing header parameter (パラメータ名)
                    status: 400
                    title: Bad Request
                    type: about:blank
        "401":
          description: |-
            利用者確認処理での認証失敗の場合のエラーメッセージ(2020月09版では未使用)
            契約有無確認処理での契約無しの場合のエラーメッセージ(2020月09版では未使用)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: 利用者確認処理でエラーが発生しました。
                    status: 401
                    title: ""
                    type: ""
        "500":
          description: サーバーの内部処理で異常が発生した場合のエラーメッセージ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラー発生しました。エラー:(エラー内容)
                    status: 500
                    title: ""
                    type: ""
      x-swagger-router-controller: swagger_server.controllers.search_controller
      x-openapi-router-controller: swagger_server.controllers.search_controller
components:
  schemas:
    ErrorResponse:
      title: HTTPステータスコードが4xx、500の場合のレスポンス
      required:
      - detail
      - status
      type: object
      properties:
        detail:
          type: string
          description: エラーメッセージ
        status:
          type: number
          description: HTTPステータスコード
        title:
          type: string
          description: タイトル
        type:
          type: string
          description: タイプ

