openapi: 3.0.0
info:
  title: CADDE v3 Specification 提供者 来歴管理I/F
  version: "3.0"
servers:
- url: /
paths:
  /eventwithhash/sent:
    post:
      tags:
      - Sent
      summary: API. 送信履歴登録要求
      description: |-
        送信履歴登録要求を行い、識別情報を取得する。

        Response:
        * 処理が成功した場合は200を返す。
        * 処理に失敗した場合は、2xx以外を返す。Responsesセクション参照。
      operationId: sent
      parameters:
      - name: x-cadde-provider
        in: header
        description: CADDEユーザID（提供者）
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-consumer
        in: header
        description: CADDEユーザID（利用者）
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-caddec-resource-id-for-provenance
        in: header
        description: 交換実績記録用リソースID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-token
        in: header
        description: 来歴管理者用トークン
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: ヘッダ情報に識別情報を設定
          headers:
            x-cadde-provenance:
              description: 来歴管理I/Fから受領した識別情報
              style: simple
              explode: false
              schema:
                type: string
        "400":
          description: パラメータ不正の場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: Missing header parameter (パラメータ名)
                    status: 400
                    title: Bad Request
                    type: about:blank
        "408":
          description: タイムアウトが発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラーが発生しました。エラー:(エラー内容)
                    status: 408
                    title: ""
                    type: ""
        "500":
          description: サーバーの内部処理で異常が発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラーが発生しました。エラー:(エラー内容)
                    status: 500
                    title: ""
                    type: ""
      x-openapi-router-controller: swagger_server.controllers.sent_controller
  /voucher/sent:
    post:
      tags:
      - Voucher
      summary: API. データ証憑通知（送信）要求
      description: |-
        データ証憑通知（受信）を行う。

        Response:
        * 処理が成功した場合は200を返す。
        * 処理に失敗した場合は、2xx以外を返す。Responsesセクション参照。
      operationId: voucher_sent
      parameters:
      - name: x-cadde-provider
        in: header
        description: CADDEユーザID（提供者）
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-consumer
        in: header
        description: CADDEユーザID（利用者）
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-contract-id
        in: header
        description: 取引ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-hash-get-data
        in: header
        description: |-
         ハッシュ値
         取得したデータを特定のハッシュアルゴリズムによってハッシュ化した値
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-contract-management-url
        in: header
        description: 契約管理サービスURL
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: x-cadde-contract-management-key
        in: header
        description: 契約管理サービスキー
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 処理完了のレスポンスを返す
        "400":
          description: パラメータ不正の場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: Missing header parameter (パラメータ名)
                    status: 400
                    title: Bad Request
                    type: about:blank
        "408":
          description: タイムアウトが発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラーが発生しました。エラー:(エラー内容)
                    status: 408
                    title: ""
                    type: ""
        "500":
          description: サーバーの内部処理で異常が発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラーが発生しました。エラー:(エラー内容)
                    status: 500
                    title: ""
                    type: ""
      x-openapi-router-controller: swagger_server.controllers.voucher_sent_controller
components:
  schemas:
    ErrorResponse:
      title: HTTPステータスコードが4xx、500の場合のレスポンス
      required:
      - detail
      - status
      type: object
      properties:
        detail:
          type: string
          description: エラーメッセージ
        status:
          type: number
          description: HTTPステータスコード
        title:
          type: string
          description: タイトル
        type:
          type: string
          description: タイプ

