# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, selector: object = None):  # noqa: E501
        """Body - a model defined in Swagger

        :param selector: The selector of this Body.  # noqa: E501
        :type selector: object
        """
        self.swagger_types = {
            'selector': object
        }

        self.attribute_map = {
            'selector': 'selector'
        }
        self._selector = selector

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def selector(self) -> object:
        """Gets the selector of this Body.


        :return: The selector of this Body.
        :rtype: object
        """
        return self._selector

    @selector.setter
    def selector(self, selector: object):
        """Sets the selector of this Body.


        :param selector: The selector of this Body.
        :type selector: object
        """
        if selector is None:
            raise ValueError("Invalid value for `selector`, must not be `None`")  # noqa: E501

        self._selector = selector
