# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CDLEventResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cdleventid: str = None):  # noqa: E501
        """CDLEventResponse - a model defined in Swagger

        :param cdleventid: The cdleventid of this CDLEventResponse.  # noqa: E501
        :type cdleventid: str
        """
        self.swagger_types = {
            'cdleventid': str
        }

        self.attribute_map = {
            'cdleventid': 'cdleventid'
        }
        self._cdleventid = cdleventid

    @classmethod
    def from_dict(cls, dikt) -> 'CDLEventResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CDLEventResponse of this CDLEventResponse.  # noqa: E501
        :rtype: CDLEventResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cdleventid(self) -> str:
        """Gets the cdleventid of this CDLEventResponse.


        :return: The cdleventid of this CDLEventResponse.
        :rtype: str
        """
        return self._cdleventid

    @cdleventid.setter
    def cdleventid(self, cdleventid: str):
        """Sets the cdleventid of this CDLEventResponse.


        :param cdleventid: The cdleventid of this CDLEventResponse.
        :type cdleventid: str
        """

        self._cdleventid = cdleventid
