openapi: 3.0.0
info:
  title: CADDE v1 Specification 提供者 来歴管理呼び出しI/F
  version: "1.0"
servers:
- url: /
paths:
  /eventwithhash/sent:
    post:
      tags:
      - Sent
      summary: API. 送信履歴登録要求
      description: |-
        来歴管理I/Fに対して、送信履歴登録要求を行い、識別情報を取得する。
        Response:
        * 処理が成功した場合は200を返す
        * 処理に失敗した場合は、2xx以外を返す。Responsesセクション参照。
      operationId: sent
      parameters:
      - name: provider-id
        in: header
        description: 提供者ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: consumer-id
        in: header
        description: 利用者ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: caddec-resource-id-for-provenance
        in: header
        description: 交換実績記録用リソースID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: token
        in: header
        description: 来歴管理者用トークン
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: ヘッダ情報に識別情報を設定する
          headers:
            x-cadde-provenance:
              description: 来歴管理I/Fから受領した識別情報
              style: simple
              explode: false
              schema:
                type: string
        "400":
          description: パラメータ不正の場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: Missing header parameter (パラメータ名)
                    status: 400
                    title: Bad Request
                    type: about:blank
        "408":
          description: タイムアウトが発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラー発生しました。エラー:(エラー内容)
                    status: 408
                    title: ""
                    type: ""
        "500":
          description: サーバーの内部処理で異常が発生した場合のエラーメッセージ
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    detail: エラー発生しました。エラー:(エラー内容)
                    status: 500
                    title: ""
                    type: ""
      x-swagger-router-controller: swagger_server.controllers.sent_controller
      x-openapi-router-controller: swagger_server.controllers.sent_controller
components:
  schemas:
    ErrorResponse:
      title: HTTPステータスコードが4xx、500の場合のレスポンス
      required:
      - detail
      - status
      type: object
      properties:
        detail:
          type: string
          description: エラーメッセージ
        status:
          type: number
          description: HTTPステータスコード
        title:
          type: string
          description: タイトル
        type:
          type: string
          description: タイプ

