# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.attribute_value import AttributeValue  # noqa: F401,E501
from swagger_server.models.metadata import Metadata  # noqa: F401,E501
from swagger_server import util


class Attribute(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: AttributeValue = None, type: str = None, metadata: Metadata = None):  # noqa: E501
        """Attribute - a model defined in Swagger

        :param value: The value of this Attribute.  # noqa: E501
        :type value: AttributeValue
        :param type: The type of this Attribute.  # noqa: E501
        :type type: str
        :param metadata: The metadata of this Attribute.  # noqa: E501
        :type metadata: Metadata
        """
        self.swagger_types = {
            'value': AttributeValue,
            'type': str,
            'metadata': Metadata
        }

        self.attribute_map = {
            'value': 'value',
            'type': 'type',
            'metadata': 'metadata'
        }
        self._value = value
        self._type = type
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'Attribute':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Attribute of this Attribute.  # noqa: E501
        :rtype: Attribute
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> AttributeValue:
        """Gets the value of this Attribute.


        :return: The value of this Attribute.
        :rtype: AttributeValue
        """
        return self._value

    @value.setter
    def value(self, value: AttributeValue):
        """Sets the value of this Attribute.


        :param value: The value of this Attribute.
        :type value: AttributeValue
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def type(self) -> str:
        """Gets the type of this Attribute.


        :return: The type of this Attribute.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Attribute.


        :param type: The type of this Attribute.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this Attribute.


        :return: The metadata of this Attribute.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this Attribute.


        :param metadata: The metadata of this Attribute.
        :type metadata: Metadata
        """

        self._metadata = metadata
