version: '3'
services:
  squid:
    container_name: forward-proxy
    build: .
    image: cadde-squid
    ports:
      - "3128:3128"
    volumes:
      - ./volumes/squid_initial.conf:/etc/squid/conf.d/default.conf
      - ./volumes/ssl:/etc/squid/ssl
#      - ./volumes/ssl_db:/var/lib/squid/ssl_db
    restart: always
